//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOLF_EMAIL_WITH_CALENDAR.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data   source=WOLF-DB-SQL19;initial catalog=WolfApproveCore.DEVISO;persist securi" +
            "ty info=True;user   id=wolf_deviso;password=28n28t28al0!;")]
        public string WolfApproveCoreISOConnectionString {
            get {
                return ((string)(this["WolfApproveCoreISOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=WolfApproveCore;Persist Security Info=True;User ID=" +
            "sa")]
        public string WolfApproveCoreConnectionString {
            get {
                return ((string)(this["WolfApproveCoreConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=WolfApproveCore;Persist Security Info=True;User ID=" +
            "sa;Password=pass@word1")]
        public string WolfApproveCoreConnectionString1 {
            get {
                return ((string)(this["WolfApproveCoreConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=WolfApproveCore.MBKISO;Persist Security Info=True;U" +
            "ser ID=sa;Password=pass@word1")]
        public string WolfApproveCore_MBKISOConnectionString {
            get {
                return ((string)(this["WolfApproveCore_MBKISOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.168.1.3\\spdev02;Initial Catalog=WolfApproveCore.MBKISO;User ID=sa" +
            ";Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string WolfApproveCore_MBKISOConnectionString1 {
            get {
                return ((string)(this["WolfApproveCore_MBKISOConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=WolfApproveCore.spaghetti;Persist Security Info=Tru" +
            "e;User ID=sa")]
        public string WolfApproveCore_spaghettiConnectionString {
            get {
                return ((string)(this["WolfApproveCore_spaghettiConnectionString"]));
            }
        }
    }
}
